language: node_js
sudo: false
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
matrix:
  include:
    - node_js: "0.10"
      env: JSDOM=3
    - node_js: "0.12"
      env: JSDOM=3
    - node_js: "4"
      env: JSDOM=3
    - node_js: "4"
      env: JSDOM=7
    - node_js: "5"
      env: JSDOM=3
    - node_js: "5"
      env: JSDOM=7
before_install:
  - npm i -g npm
  - npm i jsdom@$JSDOM # becomes extraneous, but overrides buster-test dependency
